name: Run Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:        
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |            
          8.0.x
          10.0.x

    - name: Install dependencies
      run: dotnet restore
      
    - name: run test        
      run: dotnet test
